### ISSUE TITLE
ModuleNotFoundError: No module named 'frontend'

### ISSUE THREAD

**Issue by cwj** [jtyoui/Jtyoui#12]
操作步骤： 
pip insatll fitz 安装未报错

import fitz 
报错 ImportError: No module named 'frontend'
请问大概是什么原因呢？

环境是python3.6版本。

具体信息如下：
(tensorflow) [root@tensorflow01 ~]# python3.6
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'

**Comment by cwj** [comment]
解决了  pip install PyMuPDF
